### ISSUE TITLE
Unknown module

### ISSUE THREAD

**Issue by Nikushavar** [Akascape/CTkColorPicker#1]
Hello, its me again. I have downloaded the original code file and tried to run the code which you wrote in readme, but it showed error "ModuleNotFoundError: No module named 'CTkColorPicker'"

**Comment by Akascape** [comment]
@Nikushavar Paste your python file just outside the CTkColorPicker folder. (where other files like readme and license are present).
This is a type of separate external module (not installable via pip). So you will need the folder everytime for any project.

**Comment by Nikushavar** [comment]
![image](https://user-images.githubusercontent.com/115483909/209428649-5fb2bffb-8c9c-476e-8b63-f89298c2117c.png)
like this? i still get module not found error

**Comment by Akascape** [comment]
@Nikushavar Yes, it should work with this. Check the spellings (Copy the example properly). 
Run the file directly using python idle mode.

**Comment by Nikushavar** [comment]
> @Nikushavar Yes, it should work with this. Check the spellings (Copy the example properly). Run the file directly using python idle mode.

I did, still get same error, opened in idle aswell, but it didn't help.

**Comment by Akascape** [comment]
@Nikushavar But it's working properly on my system.

Add this in the **top** of that example code:

```python
import sys
sys.path.append('CTkColorPicker')

from CTkColorPicker import AskColor
...
```
*If this doesn't work then write the full path of CTkColorPicker.*

**Comment by Akascape** [comment]
@Nikushavar I fixed the issue, it was just a small mistake in `__init__`. 
Download the new source code and try!

**Comment by Nikushavar** [comment]
> @Nikushavar I fixed the issue, it was just a small mistake in `__init__`. Download the new source code and try!

thanks alot ! :D

**Comment by Akascape** [comment]
@Nikushavar Is it working now?

**Comment by Nikushavar** [comment]
> @Nikushavar Is it working now?

I am on phone right now, will check soon and tell you 👍

**Comment by Nikushavar** [comment]
> @Nikushavar Is it working now?
same error sadly
```py
Traceback (most recent call last):
  File "h:\DOWNLOAD\CTkColorPicker-main\CTkColorPicker-main\main.py", line 2, in <module>
    from CTkColorPicker import AskColor
  File "h:\DOWNLOAD\CTkColorPicker-main\CTkColorPicker-main\CTkColorPicker\__init__.py", line 10, in <module>       
    from .ctk_color_picker import AskColor
  File "h:\DOWNLOAD\CTkColorPicker-main\CTkColorPicker-main\CTkColorPicker\ctk_color_picker.py", line 6, in <module>
    from colour import Color
ModuleNotFoundError: No module named 'colour'```

**Comment by Akascape** [comment]
@Nikushavar The first module error is fixed but this is a different module error. I have also fixed that. 
This time I am sure it will work. Please try 😓

**Comment by Nikushavar** [comment]
> @Nikushavar The first module error is fixed but this is a different module error. I have also fixed that. This time I am sure it will work. Please try 😓

here's screenshot from my file manager, idk if problem is incoming from there:
![image](https://user-images.githubusercontent.com/115483909/209856531-b6824683-951e-4c25-a82b-a71df4b59cfd.png)

There's weird thing, so in vscode it actually shows that CTkColorPicker was found:
![image](https://user-images.githubusercontent.com/115483909/209856355-4ad13701-5ced-4aef-be82-614af22df7ff.png)
but when i am trying to run it i get error:
```py
Traceback (most recent call last):
  File "h:\DOWNLOAD\CTkColorPicker-main\CTkColorPicker-main\main.py", line 2, in <module>
    from CTkColorPicker import AskColor
  File "h:\DOWNLOAD\CTkColorPicker-main\CTkColorPicker-main\CTkColorPicker\__init__.py", line 10, in <module>
    from .ctk_color_picker import AskColor
  File "h:\DOWNLOAD\CTkColorPicker-main\CTkColorPicker-main\CTkColorPicker\ctk_color_picker.py", line 6, in <module>
    from colour import Color
ModuleNotFoundError: No module named 'colour'```

**Comment by Akascape** [comment]
@Nikushavar if it is still showing that colour module not found then install colour module with `pip install colour`.

**Comment by Nikushavar** [comment]
> @Nikushavar if it is still showing that colour module not found then install colour module with `pip install colour`.

alright, wait

**Comment by Nikushavar** [comment]
> @Nikushavar if it is still showing that colour module not found then install colour module with `pip install colour`.

ayy it worked :D
![image](https://user-images.githubusercontent.com/115483909/209856739-221c3670-5a48-4c90-8f6a-4525700226ab.png)
thanks alot

**Comment by Akascape** [comment]
@Nikushavar Finally :)

**Comment by Nikushavar** [comment]
> @Nikushavar Finally :)

very cool project btw, i'll send link to my friends aswell 👍
