### ISSUE TITLE
Add timeout

### ISSUE THREAD

**Issue by 1Euro7Cent** [Akascape/CTkColorPicker#10]
I want to give it a timeout value (seconds or milliseconds) and for the window to close automatically after that time

for some context:

I have a server that sends GUI update commands and the GUI updates.
The server can request a color from the user and the GUI opens a color picker (this repo). The server has a timeout that the GUI also gets. Now I need to close that window to properly display the GUI again.

**Comment by Akascape** [comment]
This is more of a logic code that should be implemented in your application manually.

use `self.after(time_in_ms, lambda: color_picker.destroy())`

**Comment by Akascape** [comment]
@1Euro7Cent

**Comment by 1Euro7Cent** [comment]
Oh. That makes sense. I'll try it when I can.

And btw is it possible to be able to insert the hex code manually where it is displayed? If it is something that cannot be done quickly I'll create a new issue

**Comment by Akascape** [comment]
@1Euro7Cent you can set initial color using `.set_initial_color(hex_code)`.
But it is in beta stage and may not work for all colors.

**Comment by 1Euro7Cent** [comment]
I meant for the user. The user should be able to insert the hex code manually instead of searching. For example if I want the color #aaf27b then I don't want to search for it

**Comment by Akascape** [comment]
@1Euro7Cent Not possible in this widget. But there are alternative like https://github.com/j4321/tkColorPicker or this one: https://youtu.be/Ukn8Su-SVW4
Or, you can build a new one with the ctkcolorpicker widget but the initial color thing is in beta stage, so it's your choice.
