### ISSUE TITLE
Idea: Adding close button

### ISSUE THREAD

**Issue by Dargatos** [Akascape/CTkColorPicker#11]
So i had the idea of adding the ability to add an close button and make the OK button act as a command.
So if u need to pick a colour multiple times in a row u don't always need to reopen the window.

**Comment by Akascape** [comment]
@Dargatos Why not use the ctkcolorpicker widget in this case?

**Comment by Dargatos** [comment]
Well first off the layout but also I still want to press ok to pick the color and in the widget its putting out the color with every change if I saw that right. But yeah that sound kinda lazy of me gonna try the widget tmrw XD
