### ISSUE TITLE
Some colors act weird when the brightness is modified

### ISSUE THREAD

**Issue by helloHackYnow** [Akascape/CTkColorPicker#2]
I think it's because of the use of module colour.
I think I resolved it in my fork with getting rid of the use of this module.

(I'm new to github so perhaps I did not submit the issue correcly, please forgive me)

**Comment by Akascape** [comment]
@helloHackYnow Yes, this is a issue with the colour module. It generates irrelevent range of colors. 
But if you find any other **easy way** of generating the color ranges, then please do share :)
(Give a PR.)

**Comment by helloHackYnow** [comment]
Can I make a pull request ?

**Comment by helloHackYnow** [comment]
ho sorry didn't see your last line
