### ISSUE TITLE
Would it be possible to publish the project on PyPI ?

### ISSUE THREAD

**Issue by helloHackYnow** [Akascape/CTkColorPicker#4]

**Comment by Akascape** [comment]
@helloHackYnow Yes, I can upload. 
But I didn't upload it as it is a small module and also dependent on customtkinter.

**Comment by helloHackYnow** [comment]
@Akascape  I am thinking to use this project on one of my other project ( a 2d gravitationnal simulation ).
I would love to know any other way than PyPI for the color picker to stay updated in my project !

**Comment by Akascape** [comment]
@helloHackYnow I don't think I will do major updates for this project besides code correction or small adjustments. But still, let me decide...😓

**Comment by Akascape** [comment]
Ok @helloHackYnow,
I uploaded the package to my pypi account:
https://pypi.org/project/CTkColorPicker/

```
pip install CTkColorPicker
```

**Comment by helloHackYnow** [comment]
Thank you very much ! You just made the implementation much easier !

**Comment by helloHackYnow** [comment]
My project is not public yet, but the color picker is looking fantastic in it !
